[versions]
acu = "3.3.1"
aea = "95f13798d1"
amecs = "1.1.5+mc21w16a"
autoconfig = "3.2.2"
apoli = "2.5.0"
backslot = "3476614"
betterGraves = "0.4.0"
bewitchment = "3637935" # v1.18-9
biomeMakeover = "3634309" # v1.18.1-1.4.4
bumblezone = "3646901" # v4.3.1
calio = "1.7.0"
collective = "3821256" # 4.27
eldritchMobs = "734d5fc"
fallflyinglib = "3.0.0-beta.2"
flk = "1.6.0+kotlin.1.5.0"
golemsGalore = "3328376" # v1.0.0+mc1.17
haema = "1.9.9+1.18.2"
libgui = "3.3.5+1.16.5"
mobz = "3498091"
modmenu = "3.0.0"
omegaConfig = "1.2.1-1.18.1"
origins = "1.6.2"
patchouli = "1.18-61-FABRIC-SNAPSHOT"
pehkui = "3.1.0"
reach = "2.1.1"
shea = "1.0.1"
snowmercy = "3253604" # v1.0.5
somnus = "0.0.14-1.17.1"
structurized = "1.4.0+1.18"
trinkets = "3.4.0"
wood = "2.0.2"

[libraries]
apoli =         { group = "com.github.apace100",     name = "apoli", version.ref = "apoli" }
additionalEntityAttributes = { module = "com.github.DaFuqs:AdditionalEntityAttributes", version.ref = "aea" }
betterGraves =  { group = "io.github.CerulanLumina", name = "better-graves", version.ref = "betterGraves"}
bewitchment =   { group = "curse.maven",             name = "bewitchment-394915", version.ref = "bewitchment"}
biomeMakeover = { group = "curse.maven",             name = "biome-makeover-412182", version.ref = "biomeMakeover" }
bumblezone =    { group = "curse.maven",             name = "the-bumblezone-fabric-363949", version.ref = "bumblezone" }
calio =         { group = "com.github.apace100",     name = "calio", version.ref = "calio" }
collective =    { group = "curse.maven", name = "collective-fabric-526606", version.ref="collective"}
eldritchMobs =  { group = "io.github.HyperPigeon",   name = "Eldritch-Mobs", version.ref = "eldritchMobs" }
flk =           { group = "net.fabricmc",            name = "fabric-language-kotlin", version.ref = "flk" }
golemsGalore =  { group = "curse.maven",             name = "golems-galore-387197", version.ref = "golemsGalore" }
haema =         { group = "com.williambl.haema",     name = "haema", version.ref = "haema" }
libgui =        { group = "io.github.cottonmc",      name = "LibGui", version.ref = "libgui" }
mobz =          { group = "curse.maven",             name = "mobz-336554", version.ref = "mobz" }
omegaConfig =   { group = "com.github.Draylar.omega-config", name = "omega-config-base", version.ref = "omegaConfig" }
origins =       { group = "maven.modrinth",     name = "origins", version.ref = "origins" }
patchouli =     { group = "vazkii.patchouli",        name = "Patchouli", version.ref = "patchouli" }
pehkui =        { module= "com.github.Virtuoel:Pehkui", version.ref = "pehkui" }
snowmercy =     { group = "curse.maven",             name = "Snow-Mercy-429949", version.ref = "snowmercy" }
stepHeightEntityAttributes = { module = "com.github.emilyploszaj:step-height-entity-attribute", version.ref = "shea" }
structurized =  { module = "com.github.Frqnny:structurized", version.ref = "structurized" }
trinkets =      { module = "dev.emi:trinkets", version.ref = "trinkets" }
woodApi =       { module = "com.terraformersmc.terraform-api:terraform-wood-api-v1", version.ref = "wood" }

[bundles]
bewitchment = ["bewitchment", "stepHeightEntityAttributes", "patchouli", "pehkui", "trinkets", "woodApi"]
haema = ["haema", "patchouli", "flk"]
golemsGalore = ["golemsGalore", "structurized"]
origins = ["apoli", "calio", "origins"]
