[versions]
elmendorf = "0.5.2"
junit = "4.13.2"
mockito = "4.2.0"

[libraries]
elmendorf = { group = "io.github.ladysnake", name = "elmendorf", version.ref = "elmendorf" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
